src/laraveltest/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/',function(){
    return redirect()->route('user.index');
});
Route::resource('user', UserController::class)->except(['show']);
Route::get('post', [PostController::class, 'index'])->name('post.index');

src/laraveltest/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use  HasFactory;
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    //$fillableに指定したカラムのみ、create()やfill()、update()で値が代入されます。
    protected $fillable = [
        'name',
        'email',
        'birthday',
        'iscool'
    ];
}

src/laraveltest/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

src/laraveltest/app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;
//use App\Models\Post;
use Illuminate\Http\Request;
use GuzzleHttp\Client;

class PostController extends Controller
{
    public function index()
    {
            $tag_id = "laravel";

            $url = "https://qiita.com/api/v2/tags/" . $tag_id . "/items?page=1&per_page=20";
            $method = "GET";


            $client = new Client();

            $response = $client->request($method, $url);

            $posts = $response->getBody();
            $posts = json_decode($posts, true);

            return view('post.index', ['posts' => $posts]);
    }
}

src/laraveltest/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use Illuminate\Http\Request;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $users = User::all();
        return view('user.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'name' => ['required'],
            'birthday' => ['date','required'],
            'email' => ['required','unique:users','email:rfc'],
            'iscool' => ['boolean'],
        ]);
        $user = new User;

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->birthday = $request->input('birthday');
        $user->iscool = $request->input('cool') == "1";

        $user->save();

        return redirect()->route('user,.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('user.edit', compact('user'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name' => ['required'],
            'birthday' => ['date','required'],
            'email' => ['required','email:rfc'],
            'iscool' => ['boolean'],
        ]);

        $user = User::find($id);

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->birthday = $request->input('birthday');
        $user->iscool = $request->input('cool') == "1";


        $user->save();

        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();

        return redirect()->route('user.index');
    }
}

src/laraveltest/resources/views/layout/app.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>@yield('title')</title>
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/style.css') }}">
</head>
<body>
@yield('content')
</body>
</html>

src/laraveltest/resources/views/post/index.blade.php
@extends('layout.app')
@section('content')
<div class="blue-button">
    <a href="{{ route('user.index') }}"
       class="bg-yellow-500 btn hover:bg-yellow-300 font-semibold text-white py-2 px-4 rounded">
        Index
    </a>
</div>
<div class="md:container md:mx-auto">
    <table>
        <thead>
        <tr class="bg-gray-100">
            <th class="w-5/10 px-4 py-2">Title</th>
            <th class="w-1/10 px-4 py-2">Like</th>
            <th class="w-1/10 px-4 py-2">Comment</th>
            <th class="w-3/10 px-4 py-2">Created_at</th>
        </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
            <tr>
                <td class="border px-4 py-2">{{$post['title']}}</td>
                <td class="border px-4 py-2">{{$post['likes_count']}}</td>
                <td class="border px-4 py-2">{{$post['comments_count']}}</td>
                <td class="border px-4 py-2">{{$post['created_at']}}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
@endsection

src/laraveltest/resources/views/user/create.blade.php
@extends('layout.app')
@section('title','User Create')
@section('content')
    <div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
        <div class="relative py-3 sm:max-w-xl sm:mx-auto">
            <div
                class="absolute inset-0 bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl"></div>
            <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
                <div class="max-w-md mx-auto">
                    <p class="text-4xl">New Create</p>
                    <form method="POST" action="{{route('user.store')}}">
                        @csrf
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        <div class="divide-y divide-gray-200">
                            <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
                                <ul class="list-disc space-y-2">
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-name">Name</label>
                                            <input type="text" name="name" id="form-name"
                                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-indigo-600"
                                                   placeholder="user name" required>
                                        </div>
                                    </li>
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-birthday">Birthday</label>
                                            <input type="date" name="birthday" id="form-birthday"
                                                   value="{{ old('birthday') }}"
                                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-indigo-600"
                                                   placeholder="">
                                        </div>
                                    </li>
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-email">Email</label>
                                            <input type="email" name="email" id="form-email"
                                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-indigo-600"
                                                   placeholder="email">
                                        </div>
                                    </li>
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-cool">Is Cool</label>
                                            <input type="checkbox"
                                                   class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                                                   value="1" name="cool" id="form-cool">
                                        </div>
                                    </li>
                                    <div class="pt-6 text-base leading-6 font-bold sm:text-lg sm:leading-7">
                                        <p>
                                        <div class="pt-6 text-base leading-6 font-bold sm:text-lg sm:leading-7">
                                            <a href="{{ route('user.index') }}"
                                               class="bg-yellow-500 btn hover:bg-yellow-300 font-semibold text-white py-3 px-5 rounded">
                                                Index
                                            </a>
                                            <button
                                                class="bg-blue-700 btn hover:bg-blue-500 font-semibold text-white py-2 px-4 rounded"
                                                type="submit">Create
                                            </button>
                                        </div>
                                        </p>
                                    </div>
                                </ul>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

src/laraveltest/resources/views/user/edit.blade.php
@extends('layout.app')
@section('title','User Edit')
@section('content')
    <div class="min-h-screen bg-gray-100 py-6 flex flex-col justify-center sm:py-12">
        <div class="relative py-3 sm:max-w-xl sm:mx-auto">
            <div
                class="absolute inset-0 bg-gradient-to-r from-cyan-400 to-sky-500 shadow-lg transform -skew-y-6 sm:skew-y-0 sm:-rotate-6 sm:rounded-3xl"></div>
            <div class="relative px-4 py-10 bg-white shadow-lg sm:rounded-3xl sm:p-20">
                <div class="max-w-md mx-auto">
                    <p class="text-4xl">Edit</p>
                    <form method="POST" action="{{ route('user.update',$user->id) }}">
                        <input type="hidden" name="_method" value="PUT">
                        @csrf
                        @method('PUT')
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                        <div class="divide-y divide-gray-200">
                            <div class="py-8 text-base leading-6 space-y-4 text-gray-700 sm:text-lg sm:leading-7">
                                <ul class="list-disc space-y-2">
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-name">Name</label>
                                            <input type="text" name="name"
                                                   value="{{ $user->name }}"
                                                   id="form-name"
                                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-indigo-600"
                                                   required>
                                        </div>
                                    </li>
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-pass">Birthday</label>
                                            <input type="date" name="birthday" value="{{ $user->birthday }}"
                                                   id="form-pass"
                                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-indigo-600">
                                        </div>
                                    </li>
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-email">Email</label>
                                            <input type="email" name="email" value="{{ $user->email }}" id="form-email"
                                                   class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-indigo-600">
                                        </div>
                                    </li>
                                    <li class="flex items-start">
                                        <div>
                                            <label for="form-cool">Is Cool</label>
                                            <input type="checkbox" name="cool" value="1" id="form-cool"
                                                   class="rounded border-gray-300 text-indigo-600 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50"
                                                   @if (old('cool', $user->iscool) == 1) checked @endif>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="pt-6 text-base leading-6 font-bold sm:text-lg sm:leading-7">
                                <button href="{{ route('user.index') }}"
                                        class="bg-yellow-500 btn hover:bg-yellow-300 font-semibold text-white py-2 px-4 rounded">
                                    Index
                                </button>
                                <button
                                    class="bg-blue-700 btn hover:bg-blue-500 font-semibold text-white py-2 px-4 rounded"
                                    type="submit">Update
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

src/laraveltest/resources/views/user/index.blade.php
@extends('layout.app')
@section('title','Laravel Test')
@section('content')
    <div class="container">
        <div class="blue-button">
            <a href="{{ route('user.create') }}"
               class="bg-blue-700 btn hover:bg-blue-500 font-semibold text-white py-2 px-4 rounded">NEW</a>
        </div>
        <div class="yellow-button">
            <a href="{{ route('post.index') }}"
               class="bg-green-400 btn hover:bg-green-300 font-semibold text-white py-2 px-4 rounded">Qiita</a>
        </div>
    </div>
    <div class="md:container md:mx-auto">
        <table>
            <thead>
            <tr class="bg-gray-100">
                <th class="w-1/4 px-4 py-2">Name</th>
                <th class="w-1/4 px-4 py-2">Birthday</th>
                <th class="w-1/4 px-4 py-2">Email</th>
                <th class="w-1/4 px-4 py-2">Is Cool?</th>
                <th class="w-1/4 px-4 py-2"></th>
                <th class="w-1/4 px-4 py-2"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($users as $user)
                <tr>
                    <td class="border px-4 py-2">{{ $user->name }}</td>
                    <td class="border px-4 py-2">{{ $user->birthday }}</td>
                    <td class="border px-4 py-2">{{ $user->email }}</td>
                    <td class="border px-4 py-2">{{ $user->iscool }}</td>
                    <td class="border px-4 py-2">
                        <a href="{{ route('user.edit',$user->id) }}"
                           class="bg-green-700 btn hover:bg-green-500 font-semibold text-white py-2 px-4 rounded">edit</a>
                    </td>
                    <td class="border px-4 py-2">
                        <form method="POST" action="{{route('user.destroy',$user->id)}}">
                            @csrf
                            @method('delete')
                            <button type="submit"
                                    class="bg-red-700 btn hover:bg-red-500 font-semibold text-white py-2 px-4 rounded">
                                delete
                            </button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection